import type Database from "better-sqlite3";
import type { DatabaseProvider } from "./databaseConfig";
import type { ApplicationNoteRepository } from "./repositories/applicationNoteRepository";
import type { ApplicationStatusHistoryRepository } from "./repositories/applicationStatusHistoryRepository";
import type { AnalyticsRepository } from "./repositories/analyticsRepository";
import type { AppAccessConfigRepository } from "./repositories/appAccessConfigRepository";
import type { AgentApiTokenRepository } from "./repositories/agentApiTokenRepository";
import type { JobApplicationRepository } from "./repositories/jobApplicationRepository";
import type { UserRepository } from "./repositories/userRepository";
import type { ImportMode, BackupJson } from "@/lib/schemas/backup";
import type { DatabaseBackupPayload } from "./services/databaseBackupService";
import type { ImportResult } from "./services/backupService";

export type DatabaseBackend = {
  provider: DatabaseProvider;
  applications: JobApplicationRepository;
  notes: ApplicationNoteRepository;
  users: UserRepository;
  statusHistory: ApplicationStatusHistoryRepository;
  analytics: AnalyticsRepository;
  appAccessConfig?: AppAccessConfigRepository;
  agentApiTokens?: AgentApiTokenRepository;
  exportJson(): Promise<BackupJson>;
  exportSql(): Promise<string>;
  importJson(raw: unknown, mode: ImportMode): Promise<ImportResult>;
  importSql(sql: string, mode: ImportMode): Promise<ImportResult>;
  createDatabaseBackup(): Promise<DatabaseBackupPayload>;
  reset(): void;
  getSqliteDatabase?(): Database.Database;
  getSqliteDatabasePath?(): string;
};
